require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { Client } = require('clashofclans.js');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());

const CLAN_TAG = process.env.CLAN_TAG || '#2C9RRQVJR';

// Initialize Clash of Clans Client
// For Vercel dynamic IPs, we pass the Developer Portal email/password.
// The client will automatically login, get the current server IP, and create a key!
const client = new Client({
    keys: process.env.CLASH_API_TOKEN ? [process.env.CLASH_API_TOKEN] : [] // Fallback if no email is provided
});

// Auto-login to handle IP rotation (will only execute if email/password are provided)
if (process.env.COC_EMAIL && process.env.COC_PASSWORD) {
    client.login({
        email: process.env.COC_EMAIL,
        password: process.env.COC_PASSWORD,
        keyName: 'Vercel Auto Key',
        keyDescription: 'Automatically generated by Inferno Legions backend'
    }).then(() => {
        console.log('Successfully logged into Supercell Developer Portal and configured IP.');
    }).catch(err => {
        console.error('Failed to auto-login to Supercell API:', err.message);
    });
}

// Fetch Clan Details
app.get('/api/clan', async (req, res) => {
    try {
        const clan = await client.getClan(CLAN_TAG);
        // Map the properties expected by the frontend
        res.json({
            clanLevel: clan.level,
            warWins: clan.warWins,
            members: clan.memberCount,
            clanPoints: clan.points,
            badgeUrl: clan.badge.url,
            capitalHallLevel: clan.clanCapital?.capitalHallLevel || 10
        });
    } catch (error) {
        console.error('Error fetching clan:', error);
        res.status(500).json({ error: 'Failed to fetch clan data' });
    }
});

// Fetch Clan Members
app.get('/api/members', async (req, res) => {
    try {
        const members = await client.getClanMembers(CLAN_TAG);
        
        // Fetch full player data for each member to get TH level, heroes, etc.
        // We do this in chunks to avoid overwhelming the API or hitting rate limits
        const fullMembers = [];
        const chunkSize = 10;
        for (let i = 0; i < members.length; i += chunkSize) {
            const chunk = members.slice(i, i + chunkSize);
            const detailedChunk = await Promise.all(chunk.map(m => client.getPlayer(m.tag)));
            fullMembers.push(...detailedChunk);
        }
        
        // Map the detailed data back to the structure expected by the frontend
        // The frontend expects: name, tag, role, expLevel, trophies, donations, etc.
        // We now add: townHallLevel, builderBaseTrophies
        const enrichedMembers = fullMembers.map((p, index) => {
            const basic = members[index];
            return {
                ...basic,
                townHallLevel: p.townHallLevel,
                heroes: p.heroes,
                troops: p.troops
            };
        });

        res.json({ items: enrichedMembers });
    } catch (error) {
        console.error('Error fetching members:', error);
        res.status(500).json({ error: 'Failed to fetch clan members' });
    }
});

// Only listen when running directly (not on Vercel)
if (require.main === module) {
    app.listen(PORT, () => {
        console.log(`Inferno Legions Backend running on http://localhost:${PORT}`);
    });
}

module.exports = app;
